name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          TITLE: ${{ github.event.issue.title }} # By interpolating the value outside of the run CMD, GH will protect us
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
        # Interpolating the user-provided variable directly within the run CMD allows for
        # injection attacks
        # run: |
        #   issue_title="${{ github.event.issue.title }}"
        #   if [[ "$issue_title" == *"bug"* ]]; then
        #   echo "Issue is about a bug!"
        #   else
        #   echo "Issue is not about a bug"
        #   fi